/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sphinx4.encognn.hybrid;

/**
 *
 * @author Manu
 */
public class encogNeuralNet extends javax.swing.JInternalFrame {

    /**
     * Creates new form encogNeuralNet
     */
    public encogNeuralNet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFileChooser2 = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        lblSpeaker1 = new javax.swing.JLabel();
        lblSpeaker2 = new javax.swing.JLabel();
        lblSpeaker3 = new javax.swing.JLabel();
        lblSpeaker4 = new javax.swing.JLabel();
        lblSpeaker5 = new javax.swing.JLabel();
        txtSpeaker1 = new javax.swing.JTextField();
        txtSpeaker2 = new javax.swing.JTextField();
        txtSpeaker3 = new javax.swing.JTextField();
        txtSpeaker4 = new javax.swing.JTextField();
        txtSpeaker5 = new javax.swing.JTextField();
        btnSpeaker1 = new javax.swing.JButton();
        btnSpeaker2 = new javax.swing.JButton();
        btnSpeaker3 = new javax.swing.JButton();
        btnSpeaker4 = new javax.swing.JButton();
        btnSpeaker5 = new javax.swing.JButton();

        jDialog1.setAlwaysOnTop(true);
        jDialog1.setIconImage(null);
        jDialog1.setLocationByPlatform(true);
        jDialog1.setResizable(false);

        jFileChooser2.setApproveButtonText("Select");
        jFileChooser2.setDialogTitle("Open Folder for speaker 1");
        jFileChooser2.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser2.setMinimumSize(null);
        jFileChooser2.setName("Select");
        jFileChooser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDialog1.getAccessibleContext().setAccessibleParent(this);

        setClosable(true);
        setResizable(true);
        setTitle("Encog Neural Network");
        setDesktopIcon(getDesktopIcon());
        setDoubleBuffered(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel2.setForeground(new java.awt.Color(240, 240, 240));

        lblSpeaker1.setText("Speech Directory 1");

        lblSpeaker2.setText("Speech Directory 2  ");

        lblSpeaker3.setText("Speech Directory 3");

        lblSpeaker4.setText("Speech Directory 4 ");

        lblSpeaker5.setText("Speech Directory 5");

        btnSpeaker1.setText("Load Speech");
        btnSpeaker1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeaker1ActionPerformed(evt);
            }
        });

        btnSpeaker2.setText("Load Speech");
        btnSpeaker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSpeaker2ActionPerformed(evt);
            }
        });

        btnSpeaker3.setText("Load Speech");

        btnSpeaker4.setText("Load Speech");

        btnSpeaker5.setText("Load Speech");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSpeaker1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSpeaker1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSpeaker5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSpeaker5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSpeaker3)
                            .addComponent(lblSpeaker4)
                            .addComponent(lblSpeaker2))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSpeaker3)
                            .addComponent(txtSpeaker2)
                            .addComponent(txtSpeaker4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSpeaker3)
                    .addComponent(btnSpeaker1)
                    .addComponent(btnSpeaker2)
                    .addComponent(btnSpeaker4)
                    .addComponent(btnSpeaker5))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeaker1)
                    .addComponent(txtSpeaker1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpeaker1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSpeaker2)
                    .addComponent(btnSpeaker2)
                    .addComponent(lblSpeaker2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeaker3)
                    .addComponent(txtSpeaker3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpeaker3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeaker4)
                    .addComponent(txtSpeaker4)
                    .addComponent(btnSpeaker4, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSpeaker5)
                    .addComponent(txtSpeaker5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpeaker5)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSpeaker1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeaker1ActionPerformed
        // TODO add your handling code here:
        jDialog1.setTitle("Open Speech Directory");
       jDialog1.setSize(582, 400);
        jDialog1.setVisible(true);
    }//GEN-LAST:event_btnSpeaker1ActionPerformed

    private void jFileChooser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser2ActionPerformed

    private void btnSpeaker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSpeaker2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSpeaker2ActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formInternalFrameClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpeaker1;
    private javax.swing.JButton btnSpeaker2;
    private javax.swing.JButton btnSpeaker3;
    private javax.swing.JButton btnSpeaker4;
    private javax.swing.JButton btnSpeaker5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSpeaker1;
    private javax.swing.JLabel lblSpeaker2;
    private javax.swing.JLabel lblSpeaker3;
    private javax.swing.JLabel lblSpeaker4;
    private javax.swing.JLabel lblSpeaker5;
    private javax.swing.JTextField txtSpeaker1;
    private javax.swing.JTextField txtSpeaker2;
    private javax.swing.JTextField txtSpeaker3;
    private javax.swing.JTextField txtSpeaker4;
    private javax.swing.JTextField txtSpeaker5;
    // End of variables declaration//GEN-END:variables
}
