/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sphinx4.encognn.hybrid;

import javax.swing.SwingUtilities;
import sphinx4.encognn.hybrid.dict.Dictionary;

/**
 *
 * @author Manu
 */
public class mainForm extends javax.swing.JFrame {
    private boolean ssActive=false;

    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        mnuTrain = new javax.swing.JMenu();
        mnuTrain_Sphinx4 = new javax.swing.JMenuItem();
        mnuTrain_NN = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuLoadnTest = new javax.swing.JMenu();
        loadntestNN = new javax.swing.JMenuItem();
        loadntestSphinx4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 756));

        desktopPane.setBackground(new java.awt.Color(240, 240, 240));

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        mnuTrain.setText("Train");

        mnuTrain_Sphinx4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mnuTrain_Sphinx4.setText("Sphinx4");
        mnuTrain_Sphinx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrain_Sphinx4ActionPerformed(evt);
            }
        });
        mnuTrain.add(mnuTrain_Sphinx4);

        mnuTrain_NN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        mnuTrain_NN.setText("Neural Network");
        mnuTrain_NN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTrain_NNActionPerformed(evt);
            }
        });
        mnuTrain.add(mnuTrain_NN);

        fileMenu.add(mnuTrain);
        fileMenu.add(jSeparator2);

        mnuLoadnTest.setText("Load and Test");

        loadntestNN.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        loadntestNN.setMnemonic('s');
        loadntestNN.setText("Neural Network");
        loadntestNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadntestNNActionPerformed(evt);
            }
        });
        mnuLoadnTest.add(loadntestNN);

        loadntestSphinx4.setText(" Sphinx4");
        loadntestSphinx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadntestSphinx4ActionPerformed(evt);
            }
        });
        mnuLoadnTest.add(loadntestSphinx4);

        fileMenu.add(mnuLoadnTest);
        fileMenu.add(jSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('g');
        editMenu.setText("Generate");

        cutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        cutMenuItem.setMnemonic('d');
        cutMenuItem.setText("Dictionary");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void loadntestNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadntestNNActionPerformed
        // TODO add your handling code here:
        TestEncogNN tstEn=new TestEncogNN();
        desktopPane.add(tstEn);
         tstEn.setVisible(true);
        
        
    }//GEN-LAST:event_loadntestNNActionPerformed

    private void mnuTrain_Sphinx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrain_Sphinx4ActionPerformed
        // TODO add your handling code here:
        if (ssActive==false){
            
        TestSphinx4 sph=new TestSphinx4();
        desktopPane.add(sph);
        sph.setVisible(true);
        ssActive=true;
        }
    }//GEN-LAST:event_mnuTrain_Sphinx4ActionPerformed

    private void mnuTrain_NNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTrain_NNActionPerformed
        // TODO add your handling code here:
         SwingUtilities.invokeLater(new Runnable(){

            @Override
            public void run() {
                TrainEncogNN encogNeuralNet = new TrainEncogNN();
                desktopPane.add(encogNeuralNet);
                encogNeuralNet.setVisible(true);
            }
            
            
        });
       /*
        *
        TrainEncogNN n1=new TrainEncogNN();
        if (nnActive==false){
        
        desktopPane.add(n1);
        
        n1.setVisible(true);
        
        nnActive=true;
       
        
        }
       else{
        
       }
         * 
        */
    }//GEN-LAST:event_mnuTrain_NNActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        Dictionary dict =new Dictionary();
        desktopPane.add(dict);
        dict.setVisible(true);
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void loadntestSphinx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadntestSphinx4ActionPerformed
        // TODO add your handling code here:
        TestSphinx4 tstnn=new TestSphinx4();
        desktopPane.add(tstnn);
         tstnn.setVisible(true);
        
    }//GEN-LAST:event_loadntestSphinx4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem loadntestNN;
    private javax.swing.JMenuItem loadntestSphinx4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuLoadnTest;
    private javax.swing.JMenu mnuTrain;
    private javax.swing.JMenuItem mnuTrain_NN;
    private javax.swing.JMenuItem mnuTrain_Sphinx4;
    // End of variables declaration//GEN-END:variables
}
