/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sphinx4.encognn.hybrid;

import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import sphinx4.encognn.hybrid.sphinx.Transcriber;

import sphinx4.encognn.hybrid.util.FileProcessor;

/**
 *
 * @author Manu
 */
public class TestSphinx4 extends javax.swing.JInternalFrame {

    public URL CONFIGPATH ;

    /**
     * Creates new form Sphinx
     */
    public TestSphinx4() {
        try {
            this.CONFIGPATH= new File("src/sphinx4/encognn/hybrid/util/config.xml").toURI().toURL();
        } catch (MalformedURLException ex) {
            Logger.getLogger(TestSphinx4.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txtSingleWordUtter = new javax.swing.JTextField();
        btnRecogFile = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSingleRecog = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnRecogFolder = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        txtIndividualsSpokenWord = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBulkResults = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Test Sphinx4");
        setDoubleBuffered(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/sphinx4/encognn/hybrid/Icons/logo.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(491, 420));
        setPreferredSize(new java.awt.Dimension(600, 650));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Open Single Spoken File(wav)"));

        jButton1.setText("Load Spoken Word File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtSingleWordUtter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSingleWordUtterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSingleWordUtter, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSingleWordUtter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        btnRecogFile.setText("Recognize");
        btnRecogFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecogFileActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Recognized Word"));

        txtSingleRecog.setColumns(20);
        txtSingleRecog.setRows(5);
        jScrollPane1.setViewportView(txtSingleRecog);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRecogFile)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnRecogFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Test Word", jPanel1);

        jPanel3.setMinimumSize(new java.awt.Dimension(900, 500));

        btnRecogFolder.setText("Recognize");
        btnRecogFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecogFolderActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Open Single Speaker's Speech Folder"));

        jButton5.setText("Load Folder");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txtIndividualsSpokenWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIndividualsSpokenWordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(txtIndividualsSpokenWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIndividualsSpokenWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));

        txtBulkResults.setColumns(20);
        txtBulkResults.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        txtBulkResults.setRows(5);
        txtBulkResults.setDoubleBuffered(true);
        jScrollPane2.setViewportView(txtBulkResults);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRecogFolder))
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecogFolder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Test Individual Speaker's Spoken Words", jPanel3);

        getContentPane().add(jTabbedPane1);

        getAccessibleContext().setAccessibleName("Test Sphinx4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtSingleWordUtter.setText(fileDialog());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtSingleWordUtterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSingleWordUtterActionPerformed
//        // TODO add your handling code here:
//        String x;
//        Transcription trans=new Transcription();
//        x=txtSingleWordUtter.getText();
//        try {
//            txtSingleRecog.setText(trans.transcription(x));
//        } catch (MalformedURLException ex) {
//            Logger.getLogger(TestSphinx4.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (UnsupportedAudioFileException ex) {
//            Logger.getLogger(TestSphinx4.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_txtSingleWordUtterActionPerformed

    private void btnRecogFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecogFileActionPerformed

        // TODO add your handling code here:
        if (txtSingleWordUtter.getText() == "") {
            return;
        } else {
            SwingUtilities.invokeLater(new Runnable() {

                @Override
                public void run() {
                    FileProcessor fp = new FileProcessor();
                    String inputAudioFile = txtSingleWordUtter.getText();
                    File file = new File(inputAudioFile);
                    LoadnTest(file);
                }

                private void LoadnTest(File file) {
                    try {
                        System.out.println(file.getCanonicalFile());
                        Transcriber tr = new Transcriber();
                        try {
                            tr.transcribe(file.getCanonicalPath(), CONFIGPATH);
                            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                        } catch (MalformedURLException ex) {
                            Logger.getLogger(TestSphinx4.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(TestSphinx4.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } catch (IOException ex) {
                        Logger.getLogger(TestSphinx4.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
        }
    }//GEN-LAST:event_btnRecogFileActionPerformed

    private void btnRecogFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecogFolderActionPerformed
        // TODO add your handling code here:
        
        clearBulk();
        if (txtIndividualsSpokenWord.getText() == "") {
            return;
        } else {
            SwingUtilities.invokeLater(new Runnable() {

                @Override
                public void run() {
                    Transcriber t = new Transcriber();
                    FileProcessor fp = new FileProcessor();
                    String inputAudioFolder =txtIndividualsSpokenWord.getText() ;
                    //System.out.println(inputAudioFolder);// confirm source
                    List<File> files = fp.wavFileProcessor(inputAudioFolder);
                    for (File x : files) {
                        System.out.println(x.getName());
                        try {
                           txtBulkResults.append( t.transcribe(x.getCanonicalPath(), CONFIGPATH));
                        } catch (IOException ex) {
                            Logger.getLogger(TestSphinx4.class.getName()).log(Level.SEVERE, null, ex);
                       
                        } catch (UnsupportedAudioFileException ex) {
                            Logger.getLogger(TestSphinx4.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }

                private void LoadnTest(List<File> files) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

            });
        }
    }//GEN-LAST:event_btnRecogFolderActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        txtIndividualsSpokenWord.setText(Dialog());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtIndividualsSpokenWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIndividualsSpokenWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIndividualsSpokenWordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecogFile;
    private javax.swing.JButton btnRecogFolder;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtBulkResults;
    private javax.swing.JTextField txtIndividualsSpokenWord;
    private javax.swing.JTextArea txtSingleRecog;
    private javax.swing.JTextField txtSingleWordUtter;
    // End of variables declaration//GEN-END:variables

    private String Dialog() {
        String replyString = null;
        final JFileChooser fc = new JFileChooser();

        fc.setDialogTitle("Open Speech Directory");

        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setName("Select");

        int returnVal = fc.showOpenDialog(this);
        if (returnVal == 1) {

        } else {
            try {
                //System.out.println(returnVal);
                replyString = fc.getSelectedFile().getCanonicalFile().toString();
            } catch (IOException ex) {
                Logger.getLogger(encogNeuralNet.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return replyString;
    }

    private String fileDialog() {
        String replyString = null;

        final JFileChooser fc = new JFileChooser();

        fc.setDialogTitle("Open Speech Dictionary");
        fc.setFileFilter(new FileNameExtensionFilter("Dictionary File(*.dic)", "*.dic"));
        fc.setDialogType(JFileChooser.OPEN_DIALOG);
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fc.setName("Select");

        int returnVal = fc.showOpenDialog(this);
        if (returnVal == 1) {

        } else {
            try {
                //System.out.println(returnVal);
                replyString = fc.getSelectedFile().getCanonicalFile().toString();
            } catch (IOException ex) {
                Logger.getLogger(encogNeuralNet.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return replyString;
    }

    private void clearBulk() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
